import "./globals.css";
import { Inter } from "next/font/google";
import { NavbarSimple } from "./components/NavbarComponent";
import { SimpleFooter } from "./components/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mikuah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <NavbarSimple />
          <main className="flex max-w-screen-lg mx-auto justify-center grow flex-col p-6 lg:px-20 lg:py-10">
            {children}
          </main>
          <SimpleFooter />
        </div>
      </body>
    </html>
  );
}
